# Generated by Django 3.0.5 on 2021-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('searcher_id', models.CharField(max_length=20)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
