# Generated by Django 3.0.5 on 2021-02-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search_bar',
            new_name='Search',
        ),
    ]
