# Generated by Django 3.0.5 on 2021-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210203_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
