# Generated by Django 3.0.5 on 2021-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210204_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
