# Generated by Django 3.0.5 on 2021-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210204_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
