# Generated by Django 3.0.5 on 2021-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210204_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
